language: python

python:
  - "2.7"

install:
  - sudo apt-get install libevent
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_test.txt --use-mirrors

script: nosetests tests
